### ISSUE TITLE
Can you update with last versions?

### ISSUE THREAD

**Issue by 488442** [bramar2/undetectedselenium#4]

**Comment by 488442** [comment]
I have different error, can you update all project with latest version of java and selenium? Really ty

**Comment by bramar2** [comment]
I updated the old chrome for testing repo "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing" -> "https://storage.googleapis.com/chrome-for-testing-public". It should work now like the following:
```java
        // UC, driverFromCFT currently defaults to false (which only allows versions <= 113)
        UndetectedChromeDriver driver = UndetectedChromeDriver.builder()
                .driverFromCFT(true)
                .build();
        // Selenium Stealth (any chromium)
        ChromeDriver driver2 = new ChromeDriver();
        SeleniumStealthOptions.getDefault().apply(driver2);
        // Both
        UndetectedChromeDriver driver3 = UndetectedChromeDriver.builder()
                .driverFromCFT(true)
                .seleniumStealth(SeleniumStealthOptions.getDefault())
                .build();
```

**Comment by 488442** [comment]
Really thank you :)

**Comment by 488442** [comment]
Code doesnt support this Chrome Version 126.0.6478.127 ? 

Current browser version is 126.0.6478.127 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe 
Host info: host: 'LUCARIG', ip: '192.168.56.1'
Build info: version: '4.14.1', revision: '03f8ede370'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '22.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-debugging-host=127..., --remote-debugging-port=24967, --lang=it-IT, --user-data-dir=C:\Users\lu..., --no-default-browser-check, --no-first-run, --no-sandbox, --auto-open-devtools-for-tabs, --window-size=1920,1080, --start-maximized, --log-level=0], excludeSwitches: [enable-automation], extensions: []}, pageLoadStrategy: none}]}]] with root cause

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 115
Current browser version is 126.0.6478.127 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe 
Host info: host: 'LUCARIG', ip: '192.168.56.1'
Build info: version: '4.14.1', revision: '03f8ede370'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '22.0.1'

**Comment by bramar2** [comment]
Make sure your chrome binary/executable at "C:\Program Files\Google\Chrome\Application\chrome.exe" is updated to 126 and you are using the latest java Selenium version that supports it currently 4.22.0, i've also just updated it on my pom.xml.

Edit: you should just copy paste the repo code into your project so you can update the dependencies yourself.
Edit 2: make sure you're also using `.driverFromCFT(true);`

**Comment by bramar2** [comment]
I will close the ticket as it has been 2 weeks. If you have any other issues, reopen the ticket.
